version: "3.9" #Defines the version of docker compose we'll be using
services: #Defines the containers we're going to be running
  planet-server:  # This is a label for a service
    container_name: planet-container #Defines the container name
    image: restful-planet:latest #If we already created an image, we can levarage that again
    ports:
      - 9100:9100
  my-other-server:
    container_name: other-container
    image: restful-planet:latest
    ports:
      - 9200:9100
  consul-serer:
    container_name: consul-container
    image: consul:latest
    ports:
      - 8500:8500
  snake-game-server:
    container_name: snake-container
    image: ivan1993spb/snake-server
    ports:
      - 8080:8080
    command: --enable-web #Allows us to pass aditional commands when executing our container.

