
#This is a comment in a yaml file
# YAML: Yet another markup language (older name)
# YAML: YAML Ain't Markup Language 

server:  port: 9100
  
#To connect ot my db what do I need, url, username and password 
spring:
  datasource:
    url: jdbc:postgresql://database-1.cqoseij0k35s.us-east-2.rds.amazonaws.com/postgres
    username: postgres
    password: p4ssw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true